     /*USING INBUILT CLASS DATASET TO CREATE A TABLE BY FOLLOWING MOCK SHELL*/
                          /*CREATING TOTAL CATEGORY*/

data DOUBLE;
    set sashelp.class;
    output;
    Sex = 'T';
    output;
run;

       /*CRATING STATISTICS SEPARATELY FOR AGE HEIGHT AND WEIGHT VARIABLE*/

proc means data=double nway noprint;
    var age;
    class sex ;
    output out=AGEstat(drop=_:) 
    n=N std=SD max=MAX min=MIN mean=MEAN median=MEDIAN  ;
run ;

proc means data=double nway noprint;
    var height;
    class sex ;
    output out=HEIGHTstat(drop=_:) 
    n=N std=SD max=MAX min=MIN mean=MEAN median=MEDIAN  ;
run ;

proc means data=double nway noprint;
    var weight;
    class sex ;
    output out=WEIGHTstat(drop=_:) 
    n=N std=SD max=MAX min=MIN mean=MEAN median=MEDIAN  ;
run ;

proc transpose data=WEIGHTstat out=WEIGHtranss;
    id sex ;
run ;

proc transpose data=HEIGHTstat out=HEIGHtranss;
    id sex ;
run ;

proc transpose data=AGEstat out=AGEtranss;
    id sex ;
run ;

DATA AGESTREADY ;
    RETAIN Parameter _NAME_ F M T ;
    SET AGEtranss;
    IF _NAME_='N' THEN Parameter='AGE   ';
RUN ;

DATA HEIGHTSTREADY ;
    RETAIN Parameter _NAME_ F M T ;
    SET HEIGHtranss;
    IF _NAME_='N' THEN Parameter='HEIGHT';
RUN ;

              /*COMBINING 3 SEPARATELY CREATED DATASETS*/
                      /*CONTROLLING DECIMALS*/

DATA WEIGHTSTREADY ;
    RETAIN Parameter _NAME_ F M T ;
    SET WEIGHtranss;
    IF _NAME_='N' THEN Parameter='WEIGHT';
RUN ;

data REPORTREADY ;
    set AGESTREADY HEIGHTSTREADY WEIGHTSTREADY;

    NAME=UPCASE(_NAME_);
    if NAME='N' then DO ;
    FEMALE =put(F,7.0);
    MALE   =put(M,7.0);
    TOTAL  =put(T,7.0);
    END;

    ELSE IF NAME='SD' then DO ;
    FEMALE =put(F,7.2);
    MALE   =put(M,7.2);
    TOTAL  =put(T,7.2);
    END;

    ELSE IF NAME='MAX' then DO ;
    FEMALE =put(F,7.0);
    MALE   =put(M,7.0);
    TOTAL  =put(T,7.0);
    END;

    ELSE IF NAME='MIN' then DO ;
    FEMALE =put(F,7.0);
    MALE   =put(M,7.0);
    TOTAL  =put(T,7.0);
    END;

    ELSE IF NAME='MEAN' then DO ;
    FEMALE =put(F,7.1);
    MALE   =put(M,7.1);
    TOTAL  =put(T,7.1);
    END;

    ELSE IF NAME='MEDIAN' then DO ;
    FEMALE =put(F,7.2);
    MALE   =put(M,7.2);
    TOTAL  =put(T,7.2);
    END;
    DROP F M T _NAME_;
run;

                   /*FINAL STEP CREATING CUSTOMIZED REPORT*/

 ODS RTF FILE="/home/u62043545/SOURCE/TABLE.RTF" STYLE=MINIMAL;
PROC REPORT DATA=REPORTREADY HEADLINE HEADSKIP NOWD 
    STYLE=[FRAME=HSIDES RULES=GROUPS  FONT_FACE="TIMES NEW ROMAN" FONT_SIZE=8 PT] ;
    COLUMN PARAMETER NAME FEMALE MALE TOTAL;
    DEFINE PARAMETER/'PARAMETER' ORDER WIDTH=9;
    DEFINE NAME/ 'STAT' DISPLAY;
    DEFINE FEMALE/'FEMALE' DISPLAY;
    DEFINE MALE/'MALE' DISPLAY;
    DEFINE TOTAL/'TOTAL' DISPLAY;
    TITLE    'SUMMARY REPORT OF STUDENTS';
    FOOTNOTE 'GENERATED BY KRISHNA';
RUN;
 ODS RTF CLOSE;

/********************************************************************************************************/
